### ISSUE TITLE
Create an opinionated docs side nav

### ISSUE THREAD

**Issue by celestehorgan** [cncf/hugo-netlify-starter#21]
The existing side nav in this project is unopinionated. Create one which _is_ opinionated, and supports the kind of documentation structures we feel are useful for projects.

* We typically encourage projects to version within their hugo instance, i.e. `/content/1.10`, `/content/1.11`.
* Projects with translations might have the following structure: `/content/en/1.10`

**Comment by kapunahelewong** [comment]
@celestehorgan, does the left side nav of #73 accomplish what you had in mind? It's responsive, includes touch enhancements at smaller sizes, and has a show/hide when small.

**Comment by celestehorgan** [comment]
Yes @kapunahelewong, this does close it - though there's definitely a question of versioning. Let's open another issue around that?
