### ISSUE TITLE
Implement site search

### ISSUE THREAD

**Issue by celestehorgan** [cncf/hugo-netlify-starter#27]
(definitely not a 1.0 milestone requirement imho)

**Comment by nate-double-u** [comment]
Looks like a few of the CNCF sites (longhorn.io, chaos-mesh.org,  etc.) are using [Algolia](https://www.algolia.com).

Do we have a CNCF account with Algolia? Is it worth looking into?

If we want to let the projects manage this part individually, we could add a snippet to our javascript partial, like [longhorn.io has](https://github.com/longhorn/website/blob/2dcabf7cf92fd750dbdd3f8f9debb051eff8b1fa/layouts/partials/javascript.html#L30-L38), but we'd probably want to remove the actual API key and point it out in our TODO file.

**Comment by kapunahelewong** [comment]
I added a search in #73, but it was a Google Programmable Search (I hadn't seen this issue). If the Google one's ok, could we close this issue, @celestehorgan?

**Comment by celestehorgan** [comment]
Let's close this issue for now 👀
