### ISSUE TITLE
Fix `content/docs`: should be a folder not a file

### ISSUE THREAD

**Issue by nate-double-u** [cncf/hugo-netlify-starter#41]
Fix `content/docs`: should be a folder not a file.

**Comment by GauravSarkar** [comment]
i have sent a PR regarding this. please check and merge.

**Comment by GauravSarkar** [comment]
I am geeting a dco check error.Can you help me in overcoming the problem.

**Comment by nate-double-u** [comment]
Hi @GauravSarkar, thanks for looking into this!

This repo requires each commit to be signed by the developer: https://github.com/apps/dco.
To get that check to pass you'll need to amend each commit with a `Signed-off-by` line. Since this is a small PR, it may be easier to squash all the commits into one, and sign that.

**Comment by nate-double-u** [comment]
Removing bug label as this is only problematic when bringing upstream changes into sites that have already been generated from a previous version of this template where docs was a folder.
