### ISSUE TITLE
Spacing around markdown links

### ISSUE THREAD

**Issue by nate-double-u** [cncf/hugo-netlify-starter#45]
It looks like there is space being added around links, causing some punctuation to be incorrectly spaced. You can see [this issue](https://github.com/dexidp/website/issues/60) on the Dex IdP website, which is generated from this template.

If you run the site locally, you can see this on the [pod-overview page](http://localhost:1313/test-content/pod-overview/#pod-templates) where the following code:

```markdown
## Pod Templates

Pod templates are pod specifications which are included in other objects, such as
[Replication Controllers](/docs/concepts/workloads/controllers/replicationcontroller/), [Jobs](/docs/concepts/jobs/run-to-completion-finite-workloads/), and
[DaemonSets](/docs/concepts/workloads/controllers/daemonset/).  Controllers use Pod Templates to make actual pods.
The sample below is a simple manifest for a Pod which contains a container that prints
a message.
```

generates this output:
<img width="738" alt="Screen Shot 2020-10-22 at 4 50 43 PM" src="https://user-images.githubusercontent.com/4453979/96941320-a8e8ba00-14c1-11eb-9282-ee3b80e001d1.png">

**Comment by GauravSarkar** [comment]
@nate-double-u I have gone through the issue and I have certain doubts.
1)There is no pod-overview file under test-content, then how the above link is working
2)Is it spacing around the links in the Dex Idp website creation files or there is some issue in the template itself.
Little bit clarification can help me understand the problem better

**Comment by nate-double-u** [comment]
Hi @GauravSarkar, thanks for looking into this!

> 1)There is no pod-overview file under test-content, then how the above link is working

Because it's test content, you can only see it when you run the site locally: http://localhost:1313/test-content/pod-overview/#pod-templates

> 2)Is it spacing around the links in the Dex Idp website creation files or there is some issue in the template itself.

I believe that the issue is with the template itself. When you run the site locally you can see the extra spaces. I  linked to the Dex IdP site as an example because it's generated from this template, and hasn't had many changes made to the styling. Any fix made here will likely be copied downstream.

You can also replicate this bug by copying the code snippet above into the home page and running it locally.

**Comment by nate-double-u** [comment]
Just a note @GauravSarkar, I've removed the pod-templates page entirely now in favour of a smoke test page (https://cncf-hugo-starter.netlify.app/docs/test/).

I think that for testing this, we'll need to recreate the issue locally.

**Comment by GauravSarkar** [comment]
@nate-double-u  I am still looking into the matter. I have not been able to find the solution for it. Thanks for the update.

**Comment by GauravSarkar** [comment]
@nate-double-u  I wanted to understand this project completely. So I was studying the code base. If you can suggest like how should I continue so that I can properly understand what is going on in the overall project.

**Comment by nate-double-u** [comment]
Hi @GauravSarkar -- you bring up a good point, I should open a ticket to more clearly explain what this project's goals are.

With this project, we are trying to build a template that can be used, quickly and easily, by any [CNCF Sandbox Project](https://www.cncf.io/sandbox-projects/) that needs one.

**Comment by nate-double-u** [comment]
This spacing issue can be seen live [on the smoke test page in the images section](https://cncf-hugo-starter.netlify.app/docs/test/#images).

![Screen Shot 2021-07-22 at 8 58 39 PM](https://user-images.githubusercontent.com/4453979/126735856-4f43285d-1097-4808-bcfb-fdfd211d405a.png)

**Comment by kapunahelewong** [comment]
It seems like it's happening in the generated html (see extra space when inspecting), even though it's not in the markdown, which leads me to suspect the markdown parser.
<img width="385" alt="Screen Shot 2021-07-23 at 11 13 13 AM" src="https://user-images.githubusercontent.com/4116963/126804446-4dbc4260-776d-4fc7-a01c-886eafb0b754.png">

It looks like this is happening in Goldmark, but not in the previous default of BlackFriday: 
https://discourse.gohugo.io/t/white-space-issue-in-markdown/25258/2 and 
https://github.com/yuin/goldmark/issues/126
 
And there might be something in here but I haven't found it yet:
https://gohugo.io/getting-started/configuration-markup/

Anyway, adding clues that might help us track it down.

**Comment by chalin** [comment]
We've faced this problem on other websites. It arises because of the extra spaces and the "wrong" kind of comments in the link **[render hook](https://gohugo.io/getting-started/configuration-markup/#markdown-render-hooks)** file: [layouts/_default/_markup/render-link.html](https://github.com/cncf/hugo-netlify-starter/blob/main/layouts/_default/_markup/render-link.html)

Here are examples of how it's been fixed elsewhere:

- https://github.com/etcd-io/website/pull/116
- https://github.com/grpc/grpc.io/pull/203

Note that this template's `render-link.html` file has deeper problems: see #77.

**Comment by kapunahelewong** [comment]
Thank you for this, @chalin. I've opened a PR based on your fix at etcd.io but it's still showing a space. Would you take a look? I'd love any pointers you could share.

**Comment by chalin** [comment]
> Would you take a look?

Gladly. I left a comment on the PR.
