### ISSUE TITLE
Move Docs Navigation to the Left Side of Pages

### ISSUE THREAD

**Issue by nate-double-u** [cncf/hugo-netlify-starter#51]
Similar to https://github.com/dexidp/website/issues/56

As per https://dexidp.io/ feedback session, bring navigation to left side of documentation pages to be consistent with the rest of the CNCF landscape.

Things related to this shift:
* The `Edit on GitHub` button may become incorrectly placed. Similar to https://github.com/dexidp/website/issues/64
* The panel being on the left may become too wide. Similar to https://github.com/dexidp/website/issues/63

**Comment by kapunahelewong** [comment]
Closed by #73
