### ISSUE TITLE
Copyright boilerplate & LICENSE

### ISSUE THREAD

**Issue by nate-double-u** [cncf/hugo-netlify-starter#58]
As per this review conversation, https://github.com/cncf/hugo-netlify-starter/pull/40#pullrequestreview-518231324, there are questions about the copyright boilerplate we're providing with this template.

Currently the copyright footer looks as follows:
<img width="600" alt="Screen Shot 2020-11-05 at 3 28 16 PM" src="https://user-images.githubusercontent.com/4453979/98308046-1535e400-1fbf-11eb-8fdb-ac885d70292a.png">

- Is this correct as it is?
- If it isn't correct, how ~and when~ do we get guidance from legal?

**Comment by nate-double-u** [comment]
Other projects using this template:

dex
![Screen Shot 2020-11-05 at 3 51 57 PM](https://user-images.githubusercontent.com/4453979/98309483-7d39f980-1fc2-11eb-893b-47e218531562.png)

CNI
![Screen Shot 2020-11-05 at 3 52 20 PM](https://user-images.githubusercontent.com/4453979/98309489-80cd8080-1fc2-11eb-9b11-1472711c7c3b.png)

**Comment by nate-double-u** [comment]
This may be related to another issue we have: this repo doesn't have a LICENSE.

Based on this [conversation](https://github.com/dexidp/website/pull/9#issuecomment-702372163), I expect that we should probably add Apache 2.0 to this repo and keep some form of CC-BY in the template footer. I'm not sure if this being a template complicates that at all.

**Comment by nate-double-u** [comment]
Some relevant discussion: https://github.com/keptn/keptn.github.io/pull/718

**Comment by nate-double-u** [comment]
Some more relevant discussion: https://github.com/cncf/techdocs/pull/19, https://github.com/cncf/project-template/pull/12

**Comment by chalin** [comment]
In terms of copyright, the rules were simplified a little while ago, so that we can (AFAIK), have a clean footer like this one from [etcd.io](https://etcd.io/):

![image](https://user-images.githubusercontent.com/4140793/126651880-e8e0ee4f-7333-4547-b3eb-5dea035de09f.png)

**Comment by nate-double-u** [comment]
I think the question has been answered with PR https://github.com/cncf/hugo-netlify-starter/pull/63 having been merged, and @chalin's suggestion of an updated footer.

We can open an issue to update the footer.
