### ISSUE TITLE
Write up versioning best practices document

### ISSUE THREAD

**Issue by nate-double-u** [cncf/hugo-netlify-starter#60]
There are a couple ways to do versions using Hugo. 
Write a best practices document outlining the ways that work for sites of various sizes and release frequency.

Examples of versioning schemes currently in use for CNCF sites:
* https://k8s.io
* https://www.cni.dev
* https://longhorn.io/
* https://etcd.io/docs/v3.4.0/

**Comment by nate-double-u** [comment]
I've been working on the etcd.io site and [versioning came up](https://github.com/etcd-io/website/issues/82).

For sites of this scale, I think that using a folder method of versioning works better than using a URL scheme (like [Kubernetes' website](https://v1-19.docs.kubernetes.io/) does). The best example I've seen of this working is the [velero](https://velero.io) site, and their [implementation is fairly easy to follow](https://github.com/vmware-tanzu/velero/tree/main/site/layouts/docs).

**Comment by vijay938** [comment]
I want to work on this issue

**Comment by nate-double-u** [comment]
Hi @vijay938, thanks for the interest!

I've been doing [some research and thinking on versioning](https://github.com/nate-double-u/technical-documentation-versioning/wiki), and have written up a [presentation about versioning](https://github.com/nate-double-u/technical-documentation-versioning) with hugo and netlify, but haven't had the opportunity to write it into a document yet.

**Comment by nate-double-u** [comment]
I've added a versioning best practices write up over it the tech docs repo: https://github.com/cncf/techdocs/pull/25
