### ISSUE TITLE
Use license appropriate for websites: CC-by-4.0 for docs and Apache 2 for code

### ISSUE THREAD

**Issue by chalin** [cncf/hugo-netlify-starter#62]
CNCF _websites_ (and hence this website template repo), should have the following licensing terms AFAIK:

1. Website documentation is [CC by 4.0](https://creativecommons.org/licenses/by/4.0)
2. Code and code excerpts are licensed under the [Apache License, Version 2.0](https://apache.org/licenses/LICENSE-2.0)

If you agree, I'd like to suggest that this template repo have a _single_ LICENSE file containing the following text:

> Except as otherwise noted, the content of this repository is licensed under the
> Creative Commons Attribution 4.0 License [1], and code and code samples are
> licensed under the Apache License, Version 2.0 [2].
> 
> Copyright 2021-present website Authors. All rights reserved.
> 
> [1]: https://creativecommons.org/licenses/by/4.0, a copy is included below.
> [2]: https://apache.org/licenses/LICENSE-2.0
> 
> ---
> 
> Creative Commons Attribution 4.0 International
> ...

This is the [LICENSE we're using for etcd.io](https://github.com/etcd-io/website/blob/main/LICENSE).

Since 9ce9f2d835f216db463c4872b9ddf984eb4ad42f, this template repo's LICENSE only mentions (2).

cc @caniszczyk @celestehorgan @nate-double-u 

Related: #62

**Comment by chalin** [comment]
Ah, I just noticed the links that @nate-double-u added to https://github.com/cncf/hugo-netlify-starter/issues/58#issuecomment-866259850, referring to the licenses for our [techdocs](https://github.com/cncf/techdocs) repo and the [cncf/project-template](https://github.com/cncf/project-template):

> Some more relevant PRs: [cncf/techdocs#19](https://github.com/cncf/techdocs/pull/19), [cncf/project-template#12](https://github.com/cncf/project-template/pull/12)

@celestehorgan's comments in those PRs confirm the statement made in the opening comment here. Hmm, I think that licensing was discussed while I was away.

I'd like to vote for keeping things extra simple by having a **single license file** per repo mentioning the entire licensing policy, as proposed in #63.

**Comment by nate-double-u** [comment]
> Hmm, I think that licensing was discussed while I was away.

We did, I think this is the relevant slack thread: https://cloud-native.slack.com/archives/G01CSL044G0/p1624384834007600
