### ISSUE TITLE
Drop unneeded HUGO_VERSION from netlify.toml

### ISSUE THREAD

**Issue by chalin** [cncf/hugo-netlify-starter#68]
Given that this template repo uses the [hugo-extended](https://www.npmjs.com/package/hugo-extended) npm package, IMHO we don't need to (actually, shouldn't) specifying a Hugo version in `netlify.toml`:

https://github.com/cncf/hugo-netlify-starter/blob/9ce9f2d835f216db463c4872b9ddf984eb4ad42f/netlify.toml#L5-L6

Let's keep things [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) and configure the required Hugo version in only one place.

Related: #66

**Comment by kapunahelewong** [comment]
I can take this one. Is the task to remove just those two lines from `netlify.toml`?

**Comment by chalin** [comment]
Actually, let me test something first before we start on this.

**Comment by chalin** [comment]
Check complete: I wanted to ensure that there weren't going to be any problems with running the npm-fetched Hugo under macOS 10.15+. There are not permissions issues.

> I can take this one.

Thanks!

> Is the task to remove just those two lines from `netlify.toml`?

And anywhere else that a Hugo version might be mentioned -- e.g., the README file.

**Comment by chalin** [comment]
You might want to tackle #66 at the same time.

**Comment by chalin** [comment]
> And anywhere else that a Hugo version might be mentioned -- e.g., the README file.

Iif you just want to update the `netlify.toml` file for this issue, that'll be fine too.

**Comment by chalin** [comment]
Oh, I just remembered that if we use the npm-installed version of `hugo`, then you'll need to update the Makefile to use `npx hugo` everywhere a plain `hugo` is currently written.
