### ISSUE TITLE
Move deliberately-broken test link to somewhere other than the homepage?

### ISSUE THREAD

**Issue by chalin** [cncf/hugo-netlify-starter#69]
It seems strange to have the first thing one reads from the homepage be a broken link :).

Oh, and is the link checker actually working?

**Comment by nate-double-u** [comment]
Looking at the [Netlify logs](https://app.netlify.com/sites/cncf-hugo-starter/deploys/60f9d4aec5483a0007282bee) for PR #73, it doesn't look like any link checking is running on build.

**Comment by nate-double-u** [comment]
> It seems strange to have the first thing one reads from the homepage be a broken link :).

I'm not sure we need this link (and if we do, it may feel more at home on the [smoke-test page](https://cncf-hugo-starter.netlify.app/docs/demo/)). Is there a visual/behavioral difference between working and non-working links?
