### ISSUE TITLE
Specify Hugo version

### ISSUE THREAD

**Issue by paulrouget** [cncf/hugo-netlify-starter#8]
This requires Hugo 9.73+ **extended** version. This should be added somewhere in the README.

**Comment by ramprasathasokan** [comment]
I will create a PR to include it in README.

**Comment by GauravSarkar** [comment]
@nate-double-u is there any method to add the signed-off message from github interface.You suggested in my previous PR to do it via command line but I wanted to do via interface .I copied the signed-off message from the previous PR which you merged but I am still getting errot. Maybe I am doing something wrong. Help me to sort it out.

**Comment by nate-double-u** [comment]
> 9.73+ **extended** version

Do you mean v0.73+ **extended**?

**Comment by nate-double-u** [comment]
Should we also consider adding `hugo-extended` to the dependencies list in `package.json`?

**Comment by nate-double-u** [comment]
fixed with https://github.com/cncf/hugo-netlify-starter/pull/53
