### ISSUE TITLE
Add copy button to code blocks

### ISSUE THREAD

**Issue by kapunahelewong** [cncf/hugo-netlify-starter#80]
It'd be super to have a default copy button on the code blocks like this:
<img width="319" alt="Screen Shot 2021-07-23 at 3 34 23 PM" src="https://user-images.githubusercontent.com/4116963/126832596-60e1eaf9-f340-456f-8cfa-072f1aa80551.png">

I can do this!

**Comment by nate-double-u** [comment]
Added in #97
